spring:
  application:
    name: eureka-client
eureka:
  server:
    port: 9000
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
server:
  port: 9001

