server:
  port: 9004

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_routh #id
#          uri: http://localhost:9001 #匹配的路由地址
          uri: lb://system
          predicates:
            - Path=/system/** #断言路径匹配进行路由
          filters:
            - StripPrefix=1
        - id: kafka_routh
          uri: lb://kafka
          predicates:
            - Path=/kafka/**
          filters:
            - StripPrefix=1
        - id: auth_routh
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
    fetch-registry: true

# JWT Config
jwt:
  header: Authorization
  secret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALDNGhTHZ3fwCCoUF0y3GbPB8iwQU9BRkBSOTaYVFsEYENbiMjlJsRrlJmwG4+EW2plAH5AwphR8lJHXtyiWHNMCAwEAAQ==
  expiration: 7200000
  tokenHead: Bearer

