
spring:
  application:
    name: role
  datasource:
    url: jdbc:mysql://114.215.90.83:4408/test?useUnicode=true&characterEncoding=utf-8
    username: lhstest
    password: Zj123LHS
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validationQuery: select 1
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 600000
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/