spring:
  application:
    name: eureka-server
server:
  port: 9000
eureka:
  instance:
    prefer-ip-address: true # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${spring:application.name}:${server.port}
  server:
    enableSelfPreservation: false  #关闭自我保护
    eviction-interval-timer-in-ms: 1000  # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
    fetch-registry: false




